workflows:
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        BUNDLE_ID: "com.cryptowallet.app"
        XCODE_SCHEME: "CryptoWallet"
      xcode: latest
      swift: latest
    scripts:
      - name: Generate Xcode project
        script: |
          swift package generate-xcodeproj
      - name: Build debug
        script: |
          xcodebuild -project CryptoWallet.xcodeproj -scheme "$XCODE_SCHEME" -configuration Debug -destination generic/platform=iOS build
      - name: Run tests
        script: |
          swift test
    artifacts:
      - CryptoWallet.xcodeproj
      - .build
      - .swiftpm
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - build@cryptowallet.app

  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        BUNDLE_ID: "com.cryptowallet.app"
        XCODE_SCHEME: "CryptoWallet"
      xcode: latest
      swift: latest
    scripts:
      - name: Generate Xcode project
        script: |
          swift package generate-xcodeproj
      - name: Build release
        script: |
          xcodebuild -project CryptoWallet.xcodeproj -scheme "$XCODE_SCHEME" -configuration Release -destination generic/platform=iOS build
    artifacts:
      - CryptoWallet.xcodeproj
      - .build
      - .swiftpm
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - build@cryptowallet.app