workflows:
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        BUNDLE_ID: "com.cryptowallet.app"
        XCODE_PROJECT: "CryptoWallet.xcodeproj"
        XCODE_SCHEME: "CryptoWallet"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Use system default Ruby
        script: |
          rbenv global system
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then pod install; fi
      - name: Build debug
        script: |
          if [ -f "CryptoWallet.xcworkspace" ]; then
            xcodebuild build -workspace "CryptoWallet.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Debug -destination generic/platform=iOS
          else
            xcodebuild build -project "CryptoWallet.xcodeproj" -scheme "$XCODE_SCHEME" -configuration Debug -destination generic/platform=iOS
          fi
    artifacts:
      - build/Debug-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - build@cryptowallet.app
        subject: "iOS Debug Build"
        body: "CryptoWallet iOS debug build completed"
        attachments:
          - build/Debug-iphoneos/*.app

  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        BUNDLE_ID: "com.cryptowallet.app"
        XCODE_PROJECT: "CryptoWallet.xcodeproj"
        XCODE_SCHEME: "CryptoWallet"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Use system default Ruby
        script: |
          rbenv global system
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then pod install; fi
      - name: Build release
        script: |
          if [ -f "CryptoWallet.xcworkspace" ]; then
            xcodebuild build -workspace "CryptoWallet.xcworkspace" -scheme "$XCODE_SCHEME" -configuration Release -destination generic/platform=iOS
          else
            xcodebuild build -project "CryptoWallet.xcodeproj" -scheme "$XCODE_SCHEME" -configuration Release -destination generic/platform=iOS
          fi
    artifacts:
      - build/Release-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - build@cryptowallet.app
        subject: "iOS Release Build"
        body: "CryptoWallet iOS release build completed"
        attachments:
          - build/Release-iphoneos/*.app